#!C:\Users\adity\AppData\Local\Programs\Python\Python39\python.exe
print("Content-Type: text/html\r\n\r\n")    
import cgi
f=cgi.FieldStorage()
print(f.getvalue("venuename"))
print(f.getvalue("address"))
print(f.getvalue("dist"))   
print(f.getvalue("pincode"))
print(f.getvalue("state"))
print(f.getvalue("contact"))
print(f.getvalue("alt_cont"))   
print(f.getvalue("categname"))
print(f.getvalue("sername"))    
print(f.getvalue("vistname"))
print(f.getvalue("custname"))   
print(f.getvalue("adhar"))
print(f.getvalue("eventname"))
print(f.getvalue("cost"))   
print(f.getvalue("capacity"))
print(f.getvalue("amt"))   
print(f.getvalue("balance"))
print(f.getvalue("description"))
print(f.getvalue("gallery"))
print(f.getvalue("date"))