#!C:\Users\adity\AppData\Local\Programs\Python\Python39\python.exe
print("Content-Type: text/html\r\n\r\n")    
import cgi
f=cgi.FieldStorage()
print(f.getvalue("EId"))
print(f.getvalue("eventname"))
print(f.getvalue("CId"))
print(f.getvalue("VId"))   
print(f.getvalue("SId"))
print(f.getvalue("cost"))
print(f.getvalue("Edate"))
print(f.getvalue("Sdate"))   
print(f.getvalue("Edate"))
print(f.getvalue("Stime"))    
print(f.getvalue("Etime"))
print(f.getvalue("capacity"))   
print(f.getvalue("description"))
